webTibus/tibus/urls.py
from django.conf.urls.defaults import patterns

urlpatterns = patterns('tibus.views',
    (r'^$', 'index'),
    (r'^index$', 'index'),
    (r'^prediccion$', 'prediction'), 
    (r'^viaje', 'travelPrediction'),
    (r'^resultado$', 'arriveResult'),
    (r'^rViaje$', 'travelResult'),
    (r'^modelo$', 'model'), 
    (r'^contacto$', 'contact'),
    (r'^recorridos$', 'itinerary'),
)

webTibus/timetobus/urls.py
from django.conf.urls.defaults import patterns, include, url

# Uncomment the next two lines to enable the admin:
#from django.contrib import admin
#admin.autodiscover()

urlpatterns = patterns('',
    url(r'^', include('tibus.urls')),
    url(r'^', include('tibusAdmin.urls')),
    url(r'^', include('tibusWap.urls')),
    url(r'^', include('tibussphone.urls')),
    url(r'^login$', 'django.contrib.auth.views.login', {'template_name': 'login.html'}),
    url(r'^logout$', 'django.contrib.auth.views.logout', {'next_page': '/'}),
    )

webTibus/tibus/models.py
from django.db import models 

import re

'''
Enumeracion de datos usada para guardar frecuencias
'''
DIASSEMANA = (
    ('LUNES', 'Lunes'),
    ('MARTES', 'Martes'),
    ('MIERCOLES', 'Miercoles'),
    ('JUEVES', 'Jueves'),
    ('VIERNES', 'Viernes'),
    ('SABADO', 'Sabado'),
    ('DOMINGO', 'Domingo'),
)
    
class Empresa(models.Model):
    '''
    Clase que representa a un empresa
    Permite la Agrupacion de lineas, unidades y usuarios
    '''
    idempresa = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=50, help_text="Nombre de la empresa")
    mail = models.EmailField()
    
    def __unicode__(self):
        return self.nombre
    
    def getId(self):
        return self.idempresa
    
    def getName(self):
        return self.nombre
    
    def getMail(self):
        return self.mail
    
    def validate(self):
        if self.nombre == "" or self.mail == '' or re.search("[^a-zA-Z0-9]", self.nombre) :
            return False
        self.nombre = self.nombre.strip().rstrip("\n")
        return True
        
    class Meta:
        db_table = 'empresa'
            
class Recorrido(models.Model):
    '''
    Clase que representa el recorrida de una linea
    Posee una relacion uno-muchos con empresa
    '''
    idrecorrido = models.AutoField(primary_key=True) #agregado para el cambio de tablespace
    linea = models.CharField(max_length=50)
    empresa = models.ForeignKey(Empresa)
    predictable = models.BooleanField()
    
    class Meta:
        db_table = 'recorrido'
    
    def __unicode__(self):
        return self.linea
        
    def validate(self):
        if self.linea == "" or (re.search("[^a-zA-Z0-9]", self.linea)!=None):
            return False
        self.linea = self.linea.strip().rstrip("\n")
        return True
        
    def getId(self):
        return self.idrecorrido
    
    def getLinea(self):
        return self.linea
    
    def getCompany(self):
        return self.empresa
    
    def getPredictable(self):
        return self.predictable

class Parada(models.Model):
    '''
    Clase que Representa cada una de las paradas de una linea
    Posee una relacion uno-muchos con recorrido
    '''
    idparada = models.AutoField(primary_key=True) #agregado para el cambio de tablespace
    orden = models.IntegerField()
    latitud = models.FloatField()
    longitud = models.FloatField()
    linea = models.ForeignKey(Recorrido)
    calle1 = models.CharField(verbose_name="calle1", max_length=100,null=True)
    calle2 = models.CharField(verbose_name="calle2", max_length=100,null=True)
    paradaactiva = models.BooleanField(help_text="Indica si es una parada donde se detiene el colectivo o no")
    sentido = models.CharField(max_length=20)
  
    class Meta:
        db_table = 'parada'
        
    def __unicode__(self):
        nombre = str(self.calle1)
        if self.calle2 != '' and self.calle2 != None:
            nombre = nombre + ' & ' + str(self.calle2) 
        nombre = nombre + ' ('+str(self.sentido)+')'
        return nombre
          
    def getOrder(self):
        return self.orden
    
    def getLat(self):
        return self.latitud
      
    def getLon(self):
        return self.longitud
       
    def upOneOrder(self):
        self.orden = self.orden + 1
        return True
        
    def downOneOrder(self):
        self.orden = self.orden - 1
        return True
    
    def getId(self):
        return self.idparada
    
    def getLinea(self):
        return self.linea
    
    def getStreetName1(self):
        return self.calle1
    
    def getStreetName2(self):
        return self.calle2
    
    def getActive(self):
        return self.paradaactiva
    
    def getDirection(self):
        return self.sentido
    
    def validate(self):
        if self.calle1 == None or self.calle1 == '':
            return False
        if (self.latitud <= 90 and self.latitud >= -90) and (self.longitud <= 180 and self.longitud >= -180):
            self.calle1 = self.calle1.strip().rstrip("\n")
            self.calle2 = self.calle2.strip().rstrip("\n")
            return True
        return False 
        
      
class Unidad(models.Model):
    '''
    Clase que representa cada una de las unidades moviles
    Posee una relacion uno-muchos con Recorrido
    '''
    idunidad = models.AutoField(primary_key=True)
    linea = models.ForeignKey(Recorrido)
    apto_movilidad_reducida = models.BooleanField()
    id_unidad_linea = models.IntegerField()
      
    class Meta:
        db_table = 'unidad'
        
    def __unicode__(self):
        return str(self.getIdByLinea()) + " (" +str(self.linea) + ")"
    
    def getLinea(self):
        return self.linea
    
    def getId(self):
        return self.idunidad
    
    def getIdByLinea(self):
        return self.id_unidad_linea
        
    def getApto(self):
        return self.apto_movilidad_reducida
    
class Frecuencia(models.Model):
    '''
    Clase que representa los horarios de salida de las unidades de la paradas iniciales
    Posee una relacion uno-muchos con Recorrido
    '''
    idfrecuencia = models.AutoField(primary_key=True)
    linea = models.ForeignKey(Recorrido, related_name = "recorrido")
    dia_semana = models.CharField(max_length=10, choices=DIASSEMANA)
    hora = models.TimeField()
    
    def __unicode__(self):
        return str(self.dia_semana) + " " + str(self.hora)
        
    def getLinea(self):
        return self.linea
    
    def getDiaSemana(self):
        return self.dia_semana
    
    def getHora(self):
        return self.hora
        
    def getId(self):
        return self.idfrecuencia
    
    class Meta:
        db_table = 'frecuencia'

webTibus/tibus/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Fieldset, Submit
from tibus.models import Recorrido, Parada

#Formulario de datos de Prediccion de arribo de unidad a parada
class PredictionForm(forms.Form):
    '''
    Formulario para la carga de datos para prediccion de tiempo de arribo
    '''
    linea = forms.ModelChoiceField(queryset=Recorrido.objects.filter(predictable = True).order_by('linea'), empty_label='Seleccione una linea', label='Linea')
    linea.widget.attrs["onchange"]="this.form.submit()"
    orden = forms.ModelChoiceField(queryset=Parada.objects.none(), empty_label='Debe Seleccionar la linea primero', label='Parada', required=False)
    apto = forms.BooleanField(required=False, label='Vehiculo con Rampa')
    
    def __init__(self, *args, **kwargs): #inicializacion
        '''
        Inicializacion del formulario
        '''
        self.helper = FormHelper()
        self.helper.form_id = 'id-predictionForm'
        self.helper.form_method = 'post'
        
        self.helper.layout = Layout(
            Fieldset(
                'Tiempos de arribo',
                'linea',
                'orden',
                'apto',
            ),
        )
        super(PredictionForm, self).__init__(*args, **kwargs)
        
    def setQueryOrden(self, lineaId): 
        '''
        funcion que actualiza la lista de paradas al cambiar la seleccion de la linea
        '''
        self.fields['orden'].queryset = Parada.objects.filter(linea = lineaId, paradaactiva = True).order_by('orden')
        self.fields['orden'].empty_label = None
        self._errors = {}
        self.helper.add_input(Submit('action', 'resultado'))

#Formulario de datos para mostrar recorridos a usuarios        
class ItineraryForm(forms.Form):
    '''
    Formulario para la carga de datos para la visualizacion de recorridos
    '''
    linea = forms.ModelChoiceField(queryset=Recorrido.objects.all().order_by('linea'), empty_label='Seleccione una linea', label='Linea')
    linea.widget.attrs["onchange"]="this.form.submit()"
    
    def __init__(self, *args, **kwargs): #inicializacion
        '''
        Inicializacion del formulario
        '''
        self.helper = FormHelper()
        self.helper.form_id = 'id-itineraryForm'
        self.helper.form_method = 'post'
        
        self.helper.layout = Layout(
            Fieldset(
                'Recorrido y lista de paradas',
                'linea',
            ),
        )
        super(ItineraryForm, self).__init__(*args, **kwargs)
        
    def quitEmptyOption(self): 
        '''
        funcion que actualiza la lista de paradas al cambiar la seleccion de la linea
        '''
        self.fields['linea'].empty_label = None

#Formulario de datos de Prediccion de viaje        
class TravelForm(forms.Form):
    '''
    Formulario para la carga de datos para prediccion de tiempo de viaje
    '''
    linea = forms.ModelChoiceField(queryset=Recorrido.objects.filter(predictable = True).order_by('linea'), empty_label='Seleccione una linea', label='Linea')
    linea.widget.attrs["onchange"]="this.form.submit()"
    origen = forms.ModelChoiceField(queryset=Parada.objects.none(), empty_label='Debe Seleccionar la linea primero', label='Parada origen', required=False)
    destino = forms.ModelChoiceField(queryset=Parada.objects.none(), empty_label='Debe Seleccionar la linea primero', label='Parada destino', required=False)
    
    def __init__(self, *args, **kwargs):#Inicializacion
        '''
        Inicializacion del formulario
        '''
        self.helper = FormHelper()
        self.helper.form_id = 'id-travelForm'
        self.helper.form_method = 'post'
        
        self.helper.layout = Layout(
            Fieldset(
                'Tiempos de viaje',
                'linea',
                'origen',
                'destino',
            ),
        )
        super(TravelForm, self).__init__(*args, **kwargs)
        
    def setQueryOrden(self, lineaId): 
        '''
        funcion que actualiza la lista de paradas al cambiar la seleccion de la linea
        '''
        self.fields['origen'].queryset = Parada.objects.filter(linea = lineaId, paradaactiva = True).order_by('orden')
        self.fields['origen'].empty_label = None
        self.fields['destino'].queryset = Parada.objects.filter(linea = lineaId, paradaactiva = True).order_by('orden')
        self.fields['destino'].empty_label = None
        self._errors = {}
        self.helper.add_input(Submit('action', 'resultado'))

templates/ayuda.html
{% extends "baseMenu.html" %}

{% block content %}
        <div class="sombraTabla" align="center"><table style="height: 100%; width: 90%;">
            <tbody>
                <tr style="color:black;" align="left">
                    <td style="height: 100%; width: 100%;">
					<p>Datos necesarios para una estimación: Número de linea y parada Destino: se puede identificar mediante el Identificador de la parada o el nombre de las calles que forman la intersección.</p>
					<p>Interfaces disponibles: Se implementaran interfaces WEB a través de una pagina HTML y una interfaz sms.</p>
					<p>Arquitectura usada: El sistema se basa en el modelo cliente-servidor, pregunta-respuesta, esto es así para simplificar su desarrollo, escalabilidad, portabilidad y mantenimiento.</p>
					<p>Modelo de predicción: Este modelo es el algoritmo de calculo que usa el sistema para estimar los tiempos de arribo y demora. Para mas información ver la sección modelo.</p>
</td></tr></tbody></table></div>

{% endblock %}

templates/base.html
{% load url from future %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <title>{% block title %}Tibus: Sistema de prediccion de tiempos de arribo{% endblock %}</title>

    <link rel="stylesheet" type="text/css" href="{% block stylesheet %}{% load adminmedia %}{% admin_media_prefix %}css/base.css{% endblock %}" />
    {% block extrastyle %}{% endblock %}
    {% if LANGUAGE_BIDI %}<link rel="stylesheet" type="text/css" href="{% block stylesheet_rtl %}{% admin_media_prefix %}css/rtl.css{% endblock %}" />{% endif %}

    <script type="text/javascript">window.__admin_media_prefix__ = "{% filter escapejs %}{% admin_media_prefix %}{% endfilter %}";</script>
    {% block extrahead %}{% endblock %}
    {% block blockbots %}<meta name="robots" content="NONE,NOARCHIVE" />{% endblock %}	
  </head>

{% load i18n %}

<body class="{% if is_popup %}popup {% endif %}{% block bodyclass %}{% endblock %}" {% block extrabody %} {% endblock %}>

<!-- Container -->
<div id="container">

    {% if not is_popup %}
    <!-- Header -->
    <div id="header">
        <div id="branding">
        {% block branding %}{% endblock %}
        </div>
        {% if user.is_active%}
        <div id="user-tools" align=right style="font-family: Arial; font-size: 12px;">
            {% trans 'Bienvenido,' %}
            <strong>{% filter force_escape %}{% firstof user.first_name user.username %}{% endfilter %}</strong>.
            {% block userlinks %}
                {% url 'django-admindocs-docroot' as docsroot %}
                {% if docsroot %}
                    <a href="{{ docsroot }}">{% trans 'Documentacion' %}</a> /
                {% endif %}
                <a href="/">{% trans 'Home' %}</a> /
                <a href="password">
                {% trans 'Cambiar Contraseña' %}</a> /
                {% url 'logout' as logout_url %}
                {% if logout_url %}
                    <a href="{{ logout_url }}">
                {% else %}
                    <a href="{{ root_path }}logout">
                {% endif %}
                {% trans 'Desconectarse' %}</a>
            {% endblock %}
         </div>
        {% else %}
        <div id="user-tools" align=right style="font-family: Arial; font-size: 12px;">
        	<a href="login">Iniciar Sesion</a>
       	</div>
        {% endif %}
        {% block nav-global %}{% endblock %}
    </div>
    {% endif %}

        {% if messages %}
        <ul class="messagelist">{% for message in messages %}
          <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
	{% endfor %}</ul>
        {% endif %}

    <!-- Content -->
    <div id="content" Style="font-family: Arial;" class="{% block coltype %}colM{% endblock %}">
        {% block pretitle %}{% endblock %}
        {% block content_title %}{% if title %}<h1>{{ title }}</h1>{% endif %}{% endblock %}
        {% block menu %} {% endblock %}
        <div align="center">{% block content %}
        {% block object-tools %}{% endblock %}
        {{ content }}
        {% endblock %}</div>
        {% block sidebar %}{% endblock %}
        <br class="clear" />
    </div>
    <!-- END Content -->

    {% block footer %}<div id="footer"></div>{% endblock %}
</div>
<!-- END Container -->
</body>
</html>

templates/change_password.html
{% extends "baseMenu.html" %}

{% block content %}
        <div class="sombraTabla" align="center">
	        <table><tbody>
            	<tr style="color: black;" align="center"><td style="height: 100%; width: 100%;">
            		<form name="Userform" action="" method="post">{% csrf_token %}
            			<p>Cambiar contraseña de usuario {{ user }}</p>
            			<div class="form-row">{{ form.nombre }}</div>
                       	<div class="form-row"><label for="id_oldPassword" class="required">Vieja contraseña:</label> {{ form.oldPassword }}</div>
						<div class="form-row"><label for="id_newPassword" class="required">Nueva contraseña:</label> {{ form.newPassword }}</div>
						<div class="form-row"><label for="id_confirmacion" class="required">Repetir contraseña:</label> {{ form.confirmacion }}</div>
						<div class="submit-row">
						  	<input type="button" name="back" id="back" value="Volver" onClick="javaScript:history.back();">
							<input type="submit" name="changePassword" value="changePassword" />
						</div>
					</form>
				</td></tr>
				{% if error %} <tr><td style="text-align: center;"><font color="red" size=2>Error: {{ error }}</font></td></tr>{% endif %}
	      	</tbody></table>
			<script type="text/javascript">document.getElementById("id_oldPassword").focus();</script>
		</div>
{% endblock %}

templates/empresa.html
{% extends "baseMenu.html" %}

{% block content %}
<table style="text-align: left; height: 100%; width: 90%;border: 3px solid rgb(0,0,0); padding:10px; box-shadow: 0px 0px 10px 10px rgba(70,70,70, 0.4) inset;background-color:rgb(255,255,255);">
  	{% if error %} <tr><td style="text-align: center;"><font color="red" size=2>Error: {{ error }}</font></td></tr>{% endif %}
  	<tr>
  		<td style="width: 80%;" align=center >
  			<a>Empresas Existentes:</a>
  				<div id="tableContainer" class="tableContainer">
				{% if companyList %}
					<table border="0" cellpadding="0" cellspacing="0" width="100%" class="scrollTable">
						<thead class="fixedHeader">
	        				<tr>
	        					<th style="width: 50%;"><a href="#">Nombre</a></th>
	        					<th><a href="#">Email</a></th>
       					</tr></thead>
      					<tbody class="scrollContent">
        					{% for company in companyList %}<tr>
        						<td style="width: 50%;">{{ company.nombre }}</td>
        						<td>{{ company.mail}}</td>
        					</tr>
        				{% endfor %}
        			</tbody></table>
    			{% else %}<a>No empresas disponibles</a>
    			{% endif %}
		</div></td>
  		<td><form name="formEmpresa" action="" method="post">{% csrf_token %}
	       		<label for="id_empresa"> Empresa: </label> {{ form.nombre }} 
	       		<BUTTON type="submit" name="action" value="addCompany"> Agregar Empresa </BUTTON>
	       		<BUTTON type="submit" name="action" value="editCompany"> Modificar Empresa </BUTTON>
	       		<BUTTON type="submit" name="action"  value="delCompany" > Eliminar Empresa </BUTTON>
   		</form></td>
   	</tr>
</table>
{% endblock %}

{% block extrahead %}
<script type="text/javascript">
    function confirmation(){
        if (confirm("Esta seguro de querer eliminar este registro?")){
            document.formEmpresa.action = "delCompany"
            document.formEmpresa.submit();
        }
    }</script>{% endblock %}

templates/linea.html
{% extends "baseMenu.html" %}

{% block content %}
<table style="text-align: left; height: 100%; width: 90%;border: 3px solid rgb(0,0,0); padding:10px; box-shadow: 0px 0px 10px 10px rgba(70,70,70, 0.4) inset;background-color:rgb(255,255,255);">
<tr>
<td style="height: 100%; width: 80%;" align=center >
	<div id="tableContainer" class="tableContainer">
	{% if routeList %}
		<table border="0" cellpadding="0" cellspacing="0" width="100%" class="scrollTable">
			<thead class="fixedHeader">
		        <tr>
		        	<th style="width: 30%;"><a href="#">Linea</a></th>
		        	<th style="width: 30%;"><a href="#">Frecuencia</a></th>
		        	<th><a href="#">Empresa</a></th>
	        	</tr>
	       	</thead>
	       	<tbody class="scrollContent">
		      {% for route in routeList %}
		        <tr>
		        	<td style="width: 30%;">{{ route.linea }}</td>
		        	<td style="width: 30%;">{{ route.frecuencia }}</td>
		        	<td>{{ route.empresa }}</td>
	        	</tr>
		      {% endfor %}
	        </tbody>
        </table>
	{% else %}
	      <a>No lineas disponibles</a>
	{% endif %}
	</div>
</td>
<td><table>
  {% if error %} <tr><td style="text-align: center;"><font color="red" size=2>Error: {{ error }}</font></td></tr>{% endif %}
  <tr><td style="font-style: italic; font-weight: bold; color: black;font-family: Lohit Punjabi;height: 10%; width: 30%;">
  <form name = "formLinea" action="" method="post" enctype="multipart/form-data">{% csrf_token %}
  	<label for="id_empresa"> Empresa: </label> {{ form.empresa }} <br />
	<SELECT NAME="empresaCombo" SIZE=1 onchange="document.formLinea.id_empresa.value = document.formLinea.empresaCombo.options[document.formLinea.empresaCombo.selectedIndex].value;document.formLinea.empresaCombo.value=document.formLinea.empresaCombo.options[document.formLinea.empresaCombo.selectedIndex].value">
		<OPTION VALUE="all">Todas las empresas</OPTION> 
		{% for company in companyList %}
	  		<OPTION VALUE="{{ company.nombre }}">{{ company.nombre }}</OPTION>
		{% endfor %}
	</SELECT><br />
	<BUTTON type="submit" name="action" value="viewCompany"> Filtrar por Empresa </BUTTON><br />
	<label for="id_linea"> Linea: </label> {{ form.linea }} <br />
    <SELECT NAME="lineaCombo" SIZE=1 onchange="document.formLinea.id_linea.value = document.formLinea.lineaCombo.options[document.formLinea.lineaCombo.selectedIndex].value;document.formLinea.lineaCombo.value=document.formLinea.lineaCombo.options[document.formLinea.lineaCombo.selectedIndex].value">
   		<OPTION VALUE="">Seleccione un valor</OPTION>  
   		{% for route in routeList %}
   		<OPTION VALUE="{{ route.linea }}">{{ route.linea }}</OPTION>
    	{% endfor %}
   	</SELECT><br />
    </table>
    <BUTTON type="submit" name="action" value="addRoute"> Agregar Linea </BUTTON><br />
    <BUTTON type="submit" name="action" value="editRoute"> Modificar Linea </BUTTON><br />
    <BUTTON type="submit" name="action" value="delRoute" > Eliminar Linea </BUTTON><br />
    </form>
  </td></tr>
</table>
{% endblock %}

templates/prediccion.html
{% extends "baseMenu.html" %}

{% block content %}
<table style="text-align: left; height: 100%; border: 3px solid rgb(0,0,0); padding:10px; box-shadow: 0px 0px 10px 10px rgba(70,70,70, 0.4) inset;background-color:rgb(255,255,255);">
	<tbody>
		<tr><td>Seleccione la Linea y la parada</td></tr>
	  	<tr style="text-align: left; height: 20%; width: 100%;">
		  	<td><form name = "formPrediccion" action="" method="post">{% csrf_token %}
		  		<label for="id_linea"> Linea: </label> {{ form.linea }} 
		        <SELECT NAME="lineaCombo" SIZE=1 onchange="document.formPrediccion.id_linea.value = document.formPrediccion.lineaCombo.options[document.formPrediccion.lineaCombo.selectedIndex].value;document.formPrediccion.lineaCombo.value=document.formPrediccion.lineaCombo.options[document.formPrediccion.lineaCombo.selectedIndex].value;this.form.submit()">
		        	<OPTION VALUE="">Seleccione un valor</OPTION> 
		            {% for route in routeList %}
		            <OPTION {% if linea and  linea == route.linea %} SELECTED {% endif %}VALUE="{{ route.linea }}">{{ route.linea }}</OPTION>
		            {% endfor %}
		            </SELECT>
				{% if linea %}
				<br />
				<label for="id_orden"> Parada: </label> {{ form.orden }}     
		        <SELECT NAME="paradaCombo" SIZE=1 onchange="document.formPrediccion.id_orden.value = document.formPrediccion.paradaCombo.options[document.formPrediccion.paradaCombo.selectedIndex].value;document.formPrediccion.paradaCombo.value=document.formPrediccion.paradaCombo.options[document.formPrediccion.paradaCombo.selectedIndex].value">
					<OPTION VALUE="">Seleccione un valor</OPTION>
					{% for stop in stopList %}
					<OPTION VALUE="{{ stop.orden }}">{{ stop.orden }}</OPTION>
					{% endfor %}
	            </SELECT>
	            <br />
	            <label for="id_apto"> Vehiculo Especial: </label>{{ form.apto }}
	            <br />
	            <BUTTON type="submit" name="action" value="prediction">Predecir</BUTTON>
	            {% endif %}
		    </form></td>
	  	</tr>
	  	{% if error %}<tr><td style="text-align: center;"><font color="red" size=2>Error: {{ error }}</font></td></tr>{% endif %}
</tbody></table>
{% endblock %}

templates/unidaddata.html
{% extends "baseMenu.html" %}

{% block content %}
<table style="text-align: left; height: 100%;border: 3px solid rgb(0,0,0); padding:10px; box-shadow: 0px 0px 10px 10px rgba(70,70,70, 0.4) inset;background-color:rgb(255,255,255);">
	{% if mensaje %}<tr><td>{{ mensaje }}</td></tr>{% endif %}
	{% if error %} <tr><td style="text-align: center;"><font color="red" size=2>Error: {{ error }}</font></td></tr>{% endif %}
	<tr><td style="font-style: italic; font-weight: bold; color: black;font-family: Lohit Punjabi;height: 10%;">
	<form name="formUnidad" action="" method="post">{% csrf_token %}
		<table>
			<tr><td>{{ form.idbus }}</td></tr>
		    <tr>
		        <td> <label for="id_linea"> Linea: </label> {{ form.linea }} 
		        <SELECT NAME="lineaCombo" SIZE=1 onchange="document.formUnidad.id_linea.value = document.formUnidad.lineaCombo.options[document.formUnidad.lineaCombo.selectedIndex].value;document.formUnidad.lineaCombo.value=document.formUnidad.lineaCombo.options[document.formUnidad.lineaCombo.selectedIndex].value">
		        <OPTION VALUE="">Seleccione un valor</OPTION> 
		        {% for route in routeList %}
		            <OPTION {% if temporaryBus and temporaryBus.linea == route %} SELECTED {% endif %}VALUE="{{ route.linea }}">{{ route.linea }}</OPTION>
		        {% endfor %}
		        </SELECT></td>
		    </tr>
		    <tr><td> <label for="id_unidad_linea"> Identificador: </label> {{ form.id_unidad_linea }} </td></tr>
		    <tr><td> <label for="id_apto"> Apto para movilidad reducida: </label> {{ form.apto_movilidad_reducida }} </td></tr>
		    <tr><td>{{ form.action }}</td></tr>
		</table>
		<input type="button" name="back" id="back" value="Descartar" onClick="javaScript:history.back();">
		<BUTTON type="submit" name="save" value="save"> Guardar</BUTTON>
  	</form>
	</td></tr>
</table>
{% endblock %}

{% block extrahead %}
	<script type='text/javascript'>
		function initialize(){
			document.getElementById("id_action").value = document.location.search.substr(1);
		}
	</script>
{% endblock %}